// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import { env } from '@/utils/env';

export default defineConfig({
  schema: "prisma/pg-rbac/schema.prisma",
  migrations: {
    path: "prisma/pg-rbac/migrations",
  },
  datasource: {
    url: env.str("PG_RBAC_DATABASE_URL"),
  },
});
